version: '3.8'

services:
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
      - ./mariadb-container:/home
      - ./mariadb-container/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
    networks:
      - wp-network

  php:
    build: .
    volumes:
      - ./sites/site1:/var/www/html/site1
      - ./sites/site2:/var/www/html/site2
    ports:
      - "8080:80"
    restart: always
    environment:
      DB_HOST: db:3306
      DB_PASSWORD: password
      SITE1_DB_NAME: site1
      SITE1_USERNAME: site1
      SITE1_TABLE_PREFIX: site1_

      SITE2_DB_NAME: site2
      SITE2_USERNAME: site2
      SITE2_TABLE_PREFIX: site2_

      PHP_DISPLAY_ERRORS: "Off"
      OPCACHE_VALIDATE_TIMESTAMPS: "1"
      OPCACHE_REVALIDATE_FREQ: "2"
    networks:
      - wp-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"
    restart: always
    networks:
      - wp-network
volumes:
  db_data:

networks:
  wp-network:
    driver: bridge
